// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "autoUpdateEnabled": boolean;
      "autoUpdateFreqHours": number;
      "offlineMode": boolean;
      "maxLabelsShown": number;
      "labelColor": string;
      "highlightBasicTitles": boolean;
      "derivedTitleColor": string;
      "highlightDerivedTitles": boolean;
      "basicLabelPrefix": string;
    };
  }
}
